apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: openshift-tasks
  name: openshift-tasks
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: openshift-tasks
    deploymentconfig: openshift-tasks
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: openshift-tasks
        deploymentconfig: openshift-tasks
    spec:
      containers:
      - image: docker-registry.default.svc:5000/jdeenada-pipeline-tasks-dev/openshift-tasks@sha256:21c0312946cf27d0dca76a2f21ff23a87166b439b9a8653be33e832f48bf374a
        imagePullPolicy: Always
        name: openshift-tasks
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - openshift-tasks
      from:
        kind: ImageStreamTag
        name: openshift-tasks:latest
        namespace: jdeenada-pipeline-tasks-dev
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
