kind: "Template"

apiVersion: "v1"

parameters:

- name: username

  required: true

objects:

- kind: "User"

  apiVersion: "v1"

  metadata:

    name: "${username}"

- kind: "Identity"

  apiVersion: "v1"

  metadata:

    name: "htpasswd_auth:${username}"

  providerName: "htpasswd_auth"

  providerUserName: "${username}"

- kind: "UserIdentityMapping"

  apiVersion: "v1"

  identity:

    name: "htpasswd_auth:${username}"

  user:

    name: "${username}"
